### ISSUE TITLE
As a potential supporter that lives overseas, I want to be able to sign up as an international supporter member of the Pirate Party

### ISSUE THREAD

**Issue by akjones** [ppau/project-m#14]
Acceptance Criteria:

Given an user in the Membership Type page
When select 'International citizen or have a Temporary visa' type
Then the user  can see the correct membership information in the iFrame

Given an user select  'International citizen or Temporary visa' Type
When in the Details page
Then the subheadings and references to voting will change  accordingly
And the labels and inputs will remain the same

Given an user select  'International citizen or Temporary visa' Type
When in the Confirm page
Then the user can see the correct declaration text  
And the "Check your details" part remains the same

Given an user select 'International citizen or Temporary visa' Type
When the user in the Pay What You Wang page
Then the user can see 'International Membership' in the info box

**Comment by fleur94** [comment]
Things that will change in the user flow for International Membership:
- Description in Membership Type screen.
- The subheadings and references to voting will change in the Details page (possibly by injecting different text?) The labels and inputs will remain the same though.
- In the confirm page, we will change the declaration text. The "Check your details" bit remains the same.
- In the Pay What You Want page, the info box will need to reference the International Membership instead of Full Membership.
