### ISSUE TITLE
As a potential member, I want to be able to register to become a permanent resident member of the Pirate Party

### ISSUE THREAD

**Issue by akjones** [ppau/project-m#15]
Acceptance Criteria:

Given an user in the Membership Type page
When check the Permanent Resident box
Then the user can view  'You are eligible for a Permanent Resident Membership' information in the iFrame

Given an user select Permanent Resident Type
When in the Details page
Then the user can see the correct subheadings and the references to voting 
And the labels and inputs will remain the same

Given an user select Permanent Resident Type
When in the Confirm page
Then the user can see the correct declaration text  
And the "Check your details" part remains the same

Given an user select Permanent Resident Type
When the user in the Pay What You Wang page
Then the user can see 'Permanent Resident Membership' in the info box

**Comment by fleur94** [comment]
Things that will change in the user flow for Permanent Resident:
- Description in Membership Type screen.
- The subheadings and references to voting will change in the Details page (possibly by injecting different text?) The labels and inputs will remain the same though.
- In the confirm page, we will change the declaration text. The "Check your details" bit remains the same.
- In the Pay What You Want page, the info box will need to reference the Permanent Resident membership instead of Full Membership.
