### ISSUE TITLE
As a potential supporter, I want to be able to register as a supporter member of the Pirate Party

### ISSUE THREAD

**Issue by akjones** [ppau/project-m#16]

**Comment by fleur94** [comment]
Things that will change in the user flow for Supporter Membership:
- Description in Membership Type screen.
- The subheadings and references to voting will change in the Details page (possibly by injecting different text?) The labels and inputs will remain the same though.
- In the confirm page, we will change the declaration text. The "Check your details" bit remains the same.
- In the Pay What You Want page, the info box will need to reference the Supporter Membership instead of Full Membership.
