### ISSUE TITLE
Validate member sign up so potential members get fast feedback on errors

### ISSUE THREAD

**Issue by natyoung** [ppau/project-m#26]
appropriate validations on the front & back ends...

**Comment by akjones** [comment]
if fields in an address fail validation, i'd like to know which field failed, rather than residentialAddress failed (which is what I get now). also i'd like to repopulate the form with the data i already completed.

**Comment by fleur94** [comment]
Just some general design guidance on error feedback:

Claire and I were considering this image as an example -  https://hackpad-attachments.imgix.net/hackpad.com_HiGXPZ7XiG0_p.108516_1425982366276_Screen%20Shot%202015-03-10%20at%2010.11.22.png?fit=max&w=882

So, having the error box at the top listing all the input fields that resulted in errors (but with our styling) as well as an error message next to each applicable input (with a red border instead of a red line on the side.)

Claire had started creating the error box that goes at the top, but I think she had to replace the icon and bring it to the top left, instead of the bottom left where it is currently sitting. The link to the svg error icon is here: https://thoughtworks.box.com/s/ga7zhg6b2n1q9vllzpsleubfyw2897a6

Let me know if you have any questions :)

**Comment by fleur94** [comment]
And just a minor detail, we were considering changing the red hex to #CC4756 as I just realized that it is in the Pirate Party style guide.

**Comment by akjones** [comment]
it should be possible to share the validation logic between the front and back ends. webpack should be able to package parts of the server code for the front end.

**Comment by issy-li** [comment]
Validation missing:
- Membership page need some validations, currently it can jump to the details page without ticking anything. - DONE (must answer all questions)
- Confirm page need to have validations on user checked the confirm button. - DONE
- Payment amount need validations on negative value input (e.g. -1) - DONE
- Payment Page currently can jump to the next page without filling any payment type. - DONE

**Comment by dnflyangle** [comment]
Validation missing:
  - Membership page need some validations, currently it can jump to the details page without ticking anything.
  - Confirm page need to have validations on user checked the confirm button.
  - Payment amount need validations on negative value input (e.g. -1)
  - Payment Page currently can jump to the next page without filling any payment type.

**Comment by maxwellutd** [comment]
Just need for someone to go over the validation for the form.

**Comment by Doddzy** [comment]
- Postal validation is showing up, even though we did not tick the box. Postal address appears to be showing the same validation errors as residential address. (DONE)
- Validation errors should have a red border for inputs, in addition to the labels being red. (DONE)
- Some spelling mistakes: date of birth validation is currently written as DD/MM/YYY and is missing a Y. Plus, be consistent with full stops and capitals i.e. address is missing full stops, but everything else has them. (DONE, we changed it) 
- Validation for confirm page should say "Please click the declaration checkbox and check that your details are correct before continuing," - (DONE)
- Declaration checkbox statement should be red when the error has occurred. - (DONE)
- Payment page: if both payment type and amount have not been selected, error message should only say "Please select a payment method" - (DONE)
- If payment method is chosen and 0 is typed in contribution, validation message should say "If you wish to contribute, the minimum is $1." - (DONE)
- Error box should disappear in payment page after user selects an option. - (DONE)
