### ISSUE TITLE
verify potential member's email address

### ISSUE THREAD

**Issue by akjones** [ppau/project-m#30]
at some point in the sign up flow

**Comment by fleur94** [comment]
Doing initial design research for this feature.

**Comment by fleur94** [comment]
The email flow is:
- One: user receives a verification email and clicks on the link provided.
- Two: upon clicking the link, the user gets redirected to a single page that says "Your membership has been verified"
- Three: user gets a welcome email.

Audit mode will have flags for the people who have verified. Those who have not done it will be chased down by the auditor.

---

In terms of the form design, after the user types their email in the details page, they will get instant on-the-spot feedback declaring that they will receive an email verification at the address they wrote (view image below.)

<img width="638" alt="verification" src="https://cloud.githubusercontent.com/assets/16026868/12342479/c7eb0832-bb7e-11e5-9c04-fca9ee95c617.png">

This will also be reiterated in the "finish" page, which could say: "You will soon receive a verification email at [insert email here]. Please click on the link in the email so that your membership can be verified. If you do not receive it, please contact us at [insert pirate party contact details]"

**Comment by pameck** [comment]
ok, here I go.

**Comment by pameck** [comment]
We're not doing "If the user has paid, they also get an invoice in a separate email." as part of this user story

**Comment by fleur94** [comment]
Text for verification email:

![verify email](https://cloud.githubusercontent.com/assets/16026868/12540234/ab2a3a5a-c359-11e5-8ea9-3b98b0d1c6ea.jpg)

The email links to this message on the browser:

![browser_verified](https://cloud.githubusercontent.com/assets/16026868/12540237/b9925d5c-c359-11e5-999d-5d4ef8852c87.jpg)

**Comment by fleur94** [comment]
As far as the welcome email goes, we will have a very general message for now like the one below. The Pirate Party will later customise this with a more complete welcome pack. 

---

Welcome to the Pirate Party!

You can now start participating and getting involved towards the development of a more secure and transparent Australia. 

For a list of upcoming meetings and discussions, head to pirateparty.org.au

Best,

The Pirate Party

---

**Comment by rdoh** [comment]
checking this

**Comment by rdoh** [comment]
Welcome email not done yet
