### ISSUE TITLE
refactor front end to be more "reactive"

### ISSUE THREAD

**Issue by akjones** [ppau/project-m#36]

**Comment by akjones** [comment]
started out using jest for component testing, but seems to heavyweight and couldn't get it to work - have replaced it with karma/jasmine/phantomjs

**Comment by akjones** [comment]
needs to include deploying the bundle.js!

**Comment by issy-li** [comment]
React Component missing:
- Warning at details page. CHECKED
- Postal Address is not hide/show on details page. CHECKED
- Credit/Debit payment type button is missing on payment page. CHECKED
- The close button on Finish page is a bit confusing, currently it only clear the react component instead of close the whole page. - CHECKED

Significant css style missing:
- Font need to be changed to Noto Sans for all h1 h2 h3 h4 h5 h6 CHECKED
- All the page headers behave weird because of Issy's polishing yesterday!.. CHECKED
- The divider between sub title and sub description is missing CHECKED
- The currency button on payment page need to be polished. CHECKED

**Comment by akjones** [comment]
ready for testing - akjones to test.
